USE [master]
GO

/****** Object:  Database [Certificate]    Script Date: 2016-09-09 09:42:10 ******/
CREATE DATABASE [Certificate]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Certificate', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\Certificate.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Certificate_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\Certificate_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Certificate] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Certificate].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Certificate] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Certificate] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Certificate] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Certificate] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Certificate] SET ARITHABORT OFF 
GO

ALTER DATABASE [Certificate] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Certificate] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Certificate] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Certificate] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Certificate] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Certificate] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Certificate] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Certificate] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Certificate] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Certificate] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Certificate] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Certificate] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Certificate] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Certificate] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Certificate] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Certificate] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Certificate] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Certificate] SET RECOVERY FULL 
GO

ALTER DATABASE [Certificate] SET  MULTI_USER 
GO

ALTER DATABASE [Certificate] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Certificate] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Certificate] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Certificate] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Certificate] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Certificate] SET QUERY_STORE = OFF
GO

USE [Certificate]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Certificate] SET  READ_WRITE 
GO


